imports:
    - { resource: commands.yml }

services:
    formbuilder.submitted.mailer:
        class: Frontend\Modules\FormBuilder\EventListener\FormBuilderSubmittedMailSubscriber
        arguments:
            - "@mailer_configurator"
            - "@fork.settings"
        tags:
            - { name: kernel.event_listener, event: form.submitted, method: onFormSubmitted }
