services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Backend\Modules\Sitemaps\Providers\PagesSitemapProvider:
        tags:
            - { name: sitemap.provider }
