services:
    _defaults:
        autoconfigure: true
        public: true

    Backend\Modules\MediaLibrary\Domain\MediaFolder\Command\CreateMediaFolderHandler:
        arguments:
            - "@media_library.repository.folder"

    Backend\Modules\MediaLibrary\Domain\MediaFolder\Command\UpdateMediaFolderHandler: ~

    Backend\Modules\MediaLibrary\Domain\MediaFolder\Command\DeleteMediaFolderHandler:
        arguments:
            - "@media_library.repository.folder"

    Backend\Modules\MediaLibrary\Domain\MediaGroup\Command\SaveMediaGroupHandler:
        arguments:
            - "@media_library.repository.item"

    Backend\Modules\MediaLibrary\Domain\MediaItem\Command\CreateMediaItemFromMovieUrlHandler:
        arguments:
            - "@media_library.repository.item"

    Backend\Modules\MediaLibrary\Domain\MediaItem\Command\CreateMediaItemFromLocalStorageTypeHandler:
        arguments:
            - "@media_library.repository.item"

    Backend\Modules\MediaLibrary\Domain\MediaItem\Command\DeleteMediaItemHandler:
        arguments:
            - "@media_library.repository.item"

    Backend\Modules\MediaLibrary\Domain\MediaItem\Command\UpdateMediaItemHandler: ~
