services:
    _defaults:
        autoconfigure: true
        public: true

    Backend\Modules\MediaGalleries\Domain\MediaGallery\Command\CreateMediaGalleryHandler:
        arguments:
            - "@media_galleries.repository.gallery"

    Backend\Modules\MediaGalleries\Domain\MediaGallery\Command\UpdateMediaGalleryHandler: ~

    Backend\Modules\MediaGalleries\Domain\MediaGallery\Command\DeleteMediaGalleryHandler:
        arguments:
            - "@media_galleries.repository.gallery"
            - "@media_library.repository.item"
