services:
    _defaults:
        autoconfigure: true
        public: true

    Backend\Modules\Mailmotor\Domain\Settings\Command\SaveSettingsHandler:
        arguments:
            - "@fork.settings"

    Frontend\Modules\Mailmotor\Domain\Subscription\Command\SubscriptionHandler:
        arguments:
            - "@mailmotor.subscriber"
            - "@fork.settings"

    Frontend\Modules\Mailmotor\Domain\Subscription\Command\UnsubscriptionHandler:
        arguments:
            - "@mailmotor.subscriber"
            - "@fork.settings"
